name: mygobuddy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.1.0
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  google_fonts: ^6.2.1

  image_picker: ^1.1.2
  intl: ^0.20.2
  language_picker: ^0.4.5
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.5
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.0
  webview_flutter: ^4.7.0
  file_picker: ^8.0.5
  emoji_picker_flutter: ^4.3.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  record: ^6.0.0
  just_audio: ^0.9.36
  path_provider: ^2.1.3
  geolocator: ^12.0.0
  location: ^6.0.2
  table_calendar: ^3.1.2
  mapbox_maps_flutter: ^2.10.0
  pinput: ^5.0.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.3
  camera: ^0.11.0+2
  timeago: ^3.6.1
  dotted_border: ^2.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/default_marker.png
