name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create GoogleService-Info.plist
        run: |
          cat > ios/Runner/GoogleService-Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>API_KEY</key>
            <string>\${{ secrets.IOS_GOOGLE_MAPS_API_KEY }}</string>
            <key>GCM_SENDER_ID</key>
            <string>\${{ secrets.FIREBASE_GCM_SENDER_ID }}</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.mygobuddy.app</string>
            <key>PROJECT_ID</key>
            <string>\${{ secrets.FIREBASE_PROJECT_ID }}</string>
            <key>STORAGE_BUCKET</key>
            <string>\${{ secrets.FIREBASE_STORAGE_BUCKET }}</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <false/>
            <key>IS_APPINVITE_ENABLED</key>
            <true/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>\${{ secrets.FIREBASE_GOOGLE_APP_ID_IOS }}</string>
          </dict>
          </plist>
          EOF

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app (unsigned)
        run: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/MyGoBuddy-unsigned.ipa Payload/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGoBuddy-unsigned-ipa
          path: build/ios/ipa/MyGoBuddy-unsigned.ipa
          retention-days: 30

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: |
            build/ios/Build/
            ios/Pods/
          retention-days: 7
